import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';
import { createHash } from 'node:crypto';
import { Buffer } from 'node:buffer';
import { toHex } from '@midnight-ntwrk/midnight-js/utils';
import { getNetworkId } from '@midnight-ntwrk/midnight-js/network-id';
import { type Logger } from 'pino';
import * as api from './api.js';
import { type Config } from './config.js';
import { registerGpsCoords, loadAdminSecretKey } from './witnesses.js';
import { pureCircuits } from '../contracts/managed/contract/index.js';
import { type DeployedGyotakCatchContract } from './common-types.js';

const contractAddressFile = (): string =>
  resolve(process.cwd(), `.contract-address.${getNetworkId()}`);
const ENV_FILE = resolve(process.cwd(), '.env');

export const loadDotenv = (): void => {
  if (!existsSync(ENV_FILE)) return;
  for (const line of readFileSync(ENV_FILE, 'utf8').split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    const value = trimmed.slice(eq + 1).trim().replace(/^["']|["']$/g, '');
    if (!(key in process.env)) {
      process.env[key] = value;
    }
  }
};
loadDotenv();

export const readSeed = (): string => {
  const seed = process.env.WALLET_SEED;
  if (!seed) {
    throw new Error('WALLET_SEED env var is required (hex-encoded seed, generated by scripts/gen-seed.mjs).');
  }
  return seed;
};

export const readContractAddress = (): string => {
  const file = contractAddressFile();
  if (!existsSync(file)) {
    throw new Error(
      `No deployed contract address at ${file}. Run the deploy command first.`,
    );
  }
  return readFileSync(file, 'utf8').trim();
};

export const textToBytes32 = (s: string): Uint8Array => {
  const enc = new TextEncoder().encode(s);
  const buf = new Uint8Array(32);
  buf.set(enc.slice(0, 32));
  return buf;
};

export const bytes32ToAscii = (b: Uint8Array): string =>
  Buffer.from(b).toString('utf8').replace(/\u0000+$/g, '');

export const hexFromBytes = (b: Uint8Array): string =>
  Array.from(b, (x) => x.toString(16).padStart(2, '0')).join('');

export const hexToBytes = (hex: string): Uint8Array => {
  const clean = hex.startsWith('0x') ? hex.slice(2) : hex;
  if (clean.length % 2 !== 0) throw new Error(`invalid hex length: ${hex}`);
  const out = new Uint8Array(clean.length / 2);
  for (let i = 0; i < out.length; i++) {
    out[i] = parseInt(clean.slice(i * 2, i * 2 + 2), 16);
  }
  return out;
};

const sha256 = async (buf: Uint8Array | ArrayBuffer): Promise<Uint8Array> => {
  const h = createHash('sha256');
  h.update(Buffer.from(buf as ArrayBuffer));
  return new Uint8Array(h.digest());
};

export const degreesToUint32 = (s: string | number): bigint => {
  const n = typeof s === 'number' ? s : Number(s);
  if (!Number.isFinite(n)) throw new Error(`invalid GPS component: ${s}`);
  // encode as signed_e7 + 2^31 so value fits in Uint<32>
  const e7 = Math.round(n * 1e7);
  const shifted = e7 + 2_147_483_648;
  if (shifted < 0 || shifted > 4_294_967_295) throw new Error(`GPS out of range: ${s}`);
  return BigInt(shifted);
};

export interface SubmitCatchRecordParams {
  batchId: string;
  region: string;
  catchDate: string;
  fishSpecies: string;
  photoHashHex: string;
  gpsLat: string | number;
  gpsLng: string | number;
}

export interface SubmitCatchRecordResult {
  txId: string;
  blockHeight: bigint | number;
  blockHash?: string;
  photoHashHex: string;
}

export const submitCatchRecord = async (
  contract: DeployedGyotakCatchContract,
  params: SubmitCatchRecordParams,
): Promise<SubmitCatchRecordResult> => {
  registerGpsCoords(params.batchId, degreesToUint32(params.gpsLat), degreesToUint32(params.gpsLng));

  const photoHash = hexToBytes(params.photoHashHex);
  if (photoHash.length !== 32) {
    throw new Error(`photoHashHex must decode to 32 bytes, got ${photoHash.length}`);
  }

  const txData = await api.recordCatch(
    contract,
    textToBytes32(params.batchId),
    textToBytes32(params.region),
    textToBytes32(params.catchDate),
    textToBytes32(params.fishSpecies),
    photoHash,
    BigInt(Math.floor(Date.now() / 1000)),
  );

  return {
    txId: txData.txId,
    blockHeight: txData.blockHeight as bigint | number,
    blockHash: txData.blockHash ?? undefined,
    photoHashHex: hexFromBytes(photoHash),
  };
};

const parseFlag = (args: string[], flag: string): string | undefined => {
  const i = args.indexOf(flag);
  if (i === -1) return undefined;
  const value = args[i + 1];
  if (value === undefined || value.startsWith('--')) {
    throw new Error(`${flag} requires a value`);
  }
  return value;
};

// Derive the owner public key from a 32-byte secret key, using the same
// domain-tagged persistentHash as the on-chain `publicKey(sk)` pure circuit.
// We invoke the compiled contract's pureCircuits so this TS-side derivation
// can never drift from the Compact source — the formula lives in one place.
const derivePublicKeyFromSk = (sk: Uint8Array): Uint8Array => {
  const out = pureCircuits.publicKey(sk);
  if (!(out instanceof Uint8Array) || out.length !== 32) {
    throw new Error(`pureCircuits.publicKey returned unexpected value: ${out}`);
  }
  return out;
};

const cmdDeploy = async (config: Config, logger: Logger, args: string[]): Promise<void> => {
  const initialOwnerHex = parseFlag(args, '--initial-owner');
  if (!initialOwnerHex) {
    throw new Error(
      'Usage: deploy --initial-owner <hex32>\n' +
      '  hex32 is the 64-char hex of the admin public key, derived from the admin secret key.\n' +
      '  Run `npm run preview -- derive-owner-pk` (or :preprod / :mainnet) to print it from the on-disk admin-sk.',
    );
  }
  const initialOwner = hexToBytes(initialOwnerHex);
  if (initialOwner.length !== 32) {
    throw new Error(`--initial-owner must decode to 32 bytes, got ${initialOwner.length}`);
  }
  api.setLogger(logger);
  const walletCtx = await api.buildWalletAndWaitForFunds(config, readSeed());
  try {
    const providers = await api.withStatus('Configuring providers', () =>
      api.configureProviders(walletCtx, config),
    );
    const contract = await api.withStatus('Deploying contract', () =>
      api.deploy(providers, initialOwner),
    );
    const address = contract.deployTxData.public.contractAddress;
    const file = contractAddressFile();
    writeFileSync(file, address);
    logger.info(
      { file, address, initialOwner: hexFromBytes(initialOwner) },
      'Saved contract address.',
    );
  } finally {
    // Save latest sync state before stop (no-op when walletStateDir not configured).
    await api.saveWalletStates(walletCtx.wallet, config.walletStateDir);
    await walletCtx.wallet.stop();
  }
};

const cmdRotateOwner = async (config: Config, logger: Logger, args: string[]): Promise<void> => {
  const newOwnerHex = parseFlag(args, '--new-owner');
  if (!newOwnerHex) {
    throw new Error(
      'Usage: rotate-owner --new-owner <hex32>\n' +
      '  hex32 is the 64-char hex of the new owner public key. The current admin secret key\n' +
      '  must be available via the admin-sk file or GYOTAK_MIDNIGHT_ADMIN_SK env var; the\n' +
      '  contract assert(publicKey(localSecretKey()) == owner) gates this call.',
    );
  }
  const newOwner = hexToBytes(newOwnerHex);
  if (newOwner.length !== 32) {
    throw new Error(`--new-owner must decode to 32 bytes, got ${newOwner.length}`);
  }
  // Fail fast if the admin secret key is unreadable, before we spin up a wallet.
  loadAdminSecretKey();

  api.setLogger(logger);
  const walletCtx = await api.buildWalletAndWaitForFunds(config, readSeed());
  try {
    const providers = await api.withStatus('Configuring providers', () =>
      api.configureProviders(walletCtx, config),
    );
    const contract = await api.joinContract(providers, readContractAddress());
    const txData = await api.withStatus('Submitting rotateOwner', () =>
      api.rotateOwner(contract, newOwner),
    );
    console.log('');
    console.log('  ─ rotateOwner TX submitted');
    console.log(`    txId:        ${txData.txId}`);
    console.log(`    blockHeight: ${txData.blockHeight}`);
    console.log(`    blockHash:   ${txData.blockHash ?? '(n/a)'}`);
    console.log(`    newOwner:    ${hexFromBytes(newOwner)}`);
    console.log('');
  } finally {
    await api.saveWalletStates(walletCtx.wallet, config.walletStateDir);
    await walletCtx.wallet.stop();
  }
};

const cmdDeriveOwnerPk = (): void => {
  // Read sk from the standard source (file or env) and print the matching pk.
  // Ergonomic helper for the deploy ritual; never logs or echoes the secret key.
  const sk = loadAdminSecretKey();
  const pk = derivePublicKeyFromSk(sk);
  console.log(hexFromBytes(pk));
};

const cmdRecordCatch = async (config: Config, logger: Logger, args: string[]): Promise<void> => {
  const [batchId, region, catchDate, fishSpecies, photoUrl, gpsLat, gpsLng] = args;
  if (!batchId || !region || !catchDate || !fishSpecies || !photoUrl || !gpsLat || !gpsLng) {
    throw new Error(
      'Usage: record-catch <batchId> <region> <catchDate> <fishSpecies> <photoUrl> <gpsLat> <gpsLng>',
    );
  }

  // Fetch photo and compute SHA-256 of its bytes.
  logger.info({ photoUrl }, 'Fetching photo for hashing...');
  const resp = await fetch(photoUrl);
  if (!resp.ok) {
    throw new Error(`Failed to fetch photo: ${resp.status} ${resp.statusText}`);
  }
  const photoBytes = new Uint8Array(await resp.arrayBuffer());
  const photoHash = await sha256(photoBytes);
  logger.info(
    { photoBytes: photoBytes.byteLength, photoHash: hexFromBytes(photoHash) },
    'photo sha256 computed',
  );

  // Provide GPS coords via a temp JSON so the witness can resolve them at runtime.
  const gpsJsonPath = resolve(process.cwd(), `.gps-${Date.now()}.json`);
  writeFileSync(
    gpsJsonPath,
    JSON.stringify({
      [batchId]: [degreesToUint32(gpsLat).toString(), degreesToUint32(gpsLng).toString()],
    }),
  );
  process.env.GPS_JSON = gpsJsonPath;

  api.setLogger(logger);
  const walletCtx = await api.buildWalletAndWaitForFunds(config, readSeed());
  try {
    const providers = await api.withStatus('Configuring providers', () =>
      api.configureProviders(walletCtx, config),
    );
    const contract = await api.joinContract(providers, readContractAddress());

    const txData = await api.withStatus('Submitting recordCatch', () =>
      api.recordCatch(
        contract,
        textToBytes32(batchId),
        textToBytes32(region),
        textToBytes32(catchDate),
        textToBytes32(fishSpecies),
        photoHash,
        BigInt(Math.floor(Date.now() / 1000)),
      ),
    );

    console.log('');
    console.log('  ─ recordCatch TX submitted');
    console.log(`    txId:        ${txData.txId}`);
    console.log(`    blockHeight: ${txData.blockHeight}`);
    console.log(`    blockHash:   ${txData.blockHash ?? '(n/a)'}`);
    console.log(`    photoHash:   ${hexFromBytes(photoHash)}`);
    console.log('');
  } finally {
    // Save latest sync state before stop (no-op when walletStateDir not configured).
    await api.saveWalletStates(walletCtx.wallet, config.walletStateDir);
    await walletCtx.wallet.stop();
  }
};

const cmdVerifyCatch = async (config: Config, logger: Logger, args: string[]): Promise<void> => {
  const [batchId] = args;
  if (!batchId) {
    throw new Error('Usage: verify-catch <batchId>');
  }
  api.setLogger(logger);
  const walletCtx = await api.buildWalletAndWaitForFunds(config, readSeed());
  try {
    const providers = await api.withStatus('Configuring providers', () =>
      api.configureProviders(walletCtx, config),
    );

    const onChain = await api.getCatchLedgerState(
      providers,
      readContractAddress() as any,
      hexFromBytes(textToBytes32(batchId)),
    );
    if (!onChain) {
      throw new Error(`No catch record found for batchId=${batchId}`);
    }

    console.log('');
    console.log('  ─ CatchRecord (read from ledger)');
    console.log(`    batchId:     ${batchId}`);
    console.log(`    region:      ${bytes32ToAscii(onChain.region)}`);
    console.log(`    catchDate:   ${bytes32ToAscii(onChain.catchDate)}`);
    console.log(`    fishSpecies: ${bytes32ToAscii(onChain.fishSpecies)}`);
    console.log(`    gpsHash:     ${hexFromBytes(onChain.gpsHash)}`);
    console.log(`    photoHash:   ${hexFromBytes(onChain.photoHash)}`);
    console.log(`    committedAt: ${onChain.committedAt} (${new Date(Number(onChain.committedAt) * 1000).toISOString()})`);
    console.log('');
  } finally {
    // Save latest sync state before stop (no-op when walletStateDir not configured).
    await api.saveWalletStates(walletCtx.wallet, config.walletStateDir);
    await walletCtx.wallet.stop();
  }
};

export const run = async (config: Config, logger: Logger): Promise<void> => {
  const [, , cmd, ...rest] = process.argv;
  try {
    switch (cmd) {
      case 'deploy':
        await cmdDeploy(config, logger, rest);
        break;
      case 'record-catch':
        await cmdRecordCatch(config, logger, rest);
        break;
      case 'verify-catch':
        await cmdVerifyCatch(config, logger, rest);
        break;
      case 'rotate-owner':
        await cmdRotateOwner(config, logger, rest);
        break;
      case 'derive-owner-pk':
        cmdDeriveOwnerPk();
        break;
      default:
        console.error(
          'Usage: cli <deploy|record-catch|verify-catch|rotate-owner|derive-owner-pk> [...args]',
        );
        process.exit(1);
    }
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    logger.error({ err: msg, stack: e instanceof Error ? e.stack : undefined }, 'Command failed.');
    process.exit(1);
  }
  logger.info('Goodbye.');
};
