import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';
import { createHash, randomBytes } from 'node:crypto';
import { Buffer } from 'node:buffer';
import { toHex } from '@midnight-ntwrk/midnight-js/utils';
import { getNetworkId } from '@midnight-ntwrk/midnight-js/network-id';
import { type Logger } from 'pino';
import * as api from './api.js';
import { type Config } from './config.js';
import { registerGpsCoords, registerGpsNonce, loadAdminSecretKey } from './witnesses.js';
import { pureCircuits } from '../contracts/managed/contract/index.js';
import { type DeployedGyotakCatchContract } from './common-types.js';

// Optional version suffix (e.g. CATCH_ADDR_SUFFIX=v2 → .contract-address.preprod.v2)
// keeps the v2 contract address in a distinct file so it never clobbers the v1
// .contract-address.<network> that the live deployment / invoice link rely on.
// Default (unset) preserves the historical filename exactly.
const contractAddressFile = (): string => {
  const suffix = process.env.CATCH_ADDR_SUFFIX ? `.${process.env.CATCH_ADDR_SUFFIX}` : '';
  return resolve(process.cwd(), `.contract-address.${getNetworkId()}${suffix}`);
};
const ENV_FILE = resolve(process.cwd(), '.env');

export const loadDotenv = (): void => {
  if (!existsSync(ENV_FILE)) return;
  for (const line of readFileSync(ENV_FILE, 'utf8').split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    const value = trimmed.slice(eq + 1).trim().replace(/^["']|["']$/g, '');
    if (!(key in process.env)) {
      process.env[key] = value;
    }
  }
};
loadDotenv();

export const readSeed = (): string => {
  const seed = process.env.WALLET_SEED;
  if (!seed) {
    throw new Error('WALLET_SEED env var is required (hex-encoded seed, generated by scripts/gen-seed.mjs).');
  }
  return seed;
};

export const readContractAddress = (): string => {
  const file = contractAddressFile();
  if (!existsSync(file)) {
    throw new Error(
      `No deployed contract address at ${file}. Run the deploy command first.`,
    );
  }
  return readFileSync(file, 'utf8').trim();
};

export const textToBytes32 = (s: string): Uint8Array => {
  const enc = new TextEncoder().encode(s);
  const buf = new Uint8Array(32);
  buf.set(enc.slice(0, 32));
  return buf;
};

export const bytes32ToAscii = (b: Uint8Array): string =>
  Buffer.from(b).toString('utf8').replace(/\u0000+$/g, '');

export const hexFromBytes = (b: Uint8Array): string =>
  Array.from(b, (x) => x.toString(16).padStart(2, '0')).join('');

export const hexToBytes = (hex: string): Uint8Array => {
  const clean = hex.startsWith('0x') ? hex.slice(2) : hex;
  if (clean.length % 2 !== 0) throw new Error(`invalid hex length: ${hex}`);
  const out = new Uint8Array(clean.length / 2);
  for (let i = 0; i < out.length; i++) {
    out[i] = parseInt(clean.slice(i * 2, i * 2 + 2), 16);
  }
  return out;
};

const sha256 = async (buf: Uint8Array | ArrayBuffer): Promise<Uint8Array> => {
  const h = createHash('sha256');
  h.update(Buffer.from(buf as ArrayBuffer));
  return new Uint8Array(h.digest());
};

export const degreesToUint32 = (s: string | number): bigint => {
  const n = typeof s === 'number' ? s : Number(s);
  if (!Number.isFinite(n)) throw new Error(`invalid GPS component: ${s}`);
  // encode as signed_e7 + 2^31 so value fits in Uint<32>
  const e7 = Math.round(n * 1e7);
  const shifted = e7 + 2_147_483_648;
  if (shifted < 0 || shifted > 4_294_967_295) throw new Error(`GPS out of range: ${s}`);
  return BigInt(shifted);
};

// ── v2: plaintext fish manifest (Vector<10, Bytes<32>>) ────────────────────
export const FISH_MANIFEST_SLOTS = 10;

const zero32 = (): Uint8Array => new Uint8Array(32);

// One species as stored in catch_reports.fish_items (D1). Only romaji and
// weight_kg are consumed here; other locale fields are ignored.
export interface FishItem {
  romaji?: string;
  weight_kg?: number | string | null;
  [k: string]: unknown;
}

/**
 * Build the on-chain fishManifest — exactly FISH_MANIFEST_SLOTS (10) slots of
 * Bytes<32> — from a catch_reports.fish_items value.
 *
 * Each species becomes a plaintext "romaji:weight_kg" string with the weight
 * kept VERBATIM (no rounding: 20.8 → "20.8", 17 → "17"). A species with no
 * weight becomes "romaji" alone. Slots are encoded via textToBytes32.
 *
 * No silent truncation:
 *  - An entry whose UTF-8 "romaji:weight" exceeds 32 bytes is SKIPPED with a
 *    console.warn (never cut to fit).
 *  - At most 10 slots are emitted; any surplus species is SKIPPED with a warn.
 *  - An entry without a romaji name is SKIPPED with a warn.
 *  - Unused slots are zero-padded (all-zero Bytes<32>).
 *
 * Accepts the raw JSON string (as stored in D1), an already-parsed array, or
 * null/empty (→ all-zero manifest).
 */
export const buildFishManifest = (
  fishItems: string | FishItem[] | null | undefined,
): Uint8Array[] => {
  let parsed: FishItem[] = [];
  if (Array.isArray(fishItems)) {
    parsed = fishItems;
  } else if (typeof fishItems === 'string' && fishItems.trim() !== '') {
    try {
      const j: unknown = JSON.parse(fishItems);
      if (Array.isArray(j)) parsed = j as FishItem[];
      else console.warn('buildFishManifest: fish_items JSON is not an array; treating as empty');
    } catch (e) {
      console.warn(
        `buildFishManifest: fish_items is not valid JSON; treating as empty (${(e as Error).message})`,
      );
    }
  }

  const slots: Uint8Array[] = [];
  for (const item of parsed) {
    if (slots.length >= FISH_MANIFEST_SLOTS) {
      console.warn(
        `buildFishManifest: more than ${FISH_MANIFEST_SLOTS} species; skipping surplus "${
          item?.romaji ?? JSON.stringify(item)
        }"`,
      );
      continue;
    }
    const romaji = typeof item?.romaji === 'string' ? item.romaji.trim() : '';
    if (romaji === '') {
      console.warn(`buildFishManifest: entry without romaji; skipping ${JSON.stringify(item)}`);
      continue;
    }
    const w = item?.weight_kg;
    const hasWeight = w !== undefined && w !== null && String(w).trim() !== '';
    const slotStr = hasWeight ? `${romaji}:${String(w)}` : romaji;
    const byteLen = new TextEncoder().encode(slotStr).length;
    if (byteLen > 32) {
      console.warn(
        `buildFishManifest: "${slotStr}" is ${byteLen} bytes (>32); skipping slot (no silent truncation)`,
      );
      continue;
    }
    slots.push(textToBytes32(slotStr));
  }

  while (slots.length < FISH_MANIFEST_SLOTS) slots.push(zero32());
  return slots;
};

export interface SubmitCatchRecordParams {
  batchId: string;
  region: string;
  catchDate: string;
  fishSpecies: string;
  // v2: pre-built 10-slot manifest (use buildFishManifest). Optional so existing
  // callers that have not yet wired the manifest default to an all-zero manifest.
  fishManifest?: Uint8Array[];
  photoHashHex: string;
  gpsLat: string | number;
  gpsLng: string | number;
  // v3: GPS bounding box for range proof (degrees, converted via degreesToUint32).
  // Required — omitting the box is a compile error, not a silent fallback.
  latMin: number;
  latMax: number;
  lonMin: number;
  lonMax: number;
}

export interface SubmitCatchRecordResult {
  txId: string;
  blockHeight: bigint | number;
  blockHash?: string;
  photoHashHex: string;
}

export const submitCatchRecord = async (
  contract: DeployedGyotakCatchContract,
  params: SubmitCatchRecordParams,
): Promise<SubmitCatchRecordResult> => {
  registerGpsCoords(params.batchId, degreesToUint32(params.gpsLat), degreesToUint32(params.gpsLng));

  const photoHash = hexToBytes(params.photoHashHex);
  if (photoHash.length !== 32) {
    throw new Error(`photoHashHex must decode to 32 bytes, got ${photoHash.length}`);
  }

  // Default to an all-zero manifest when a caller has not supplied one. When
  // supplied it must be exactly FISH_MANIFEST_SLOTS entries (the contract's
  // Vector<10> is fixed-length).
  const fishManifest = params.fishManifest ?? buildFishManifest(null);
  if (fishManifest.length !== FISH_MANIFEST_SLOTS) {
    throw new Error(
      `fishManifest must have exactly ${FISH_MANIFEST_SLOTS} slots, got ${fishManifest.length}`,
    );
  }

  const txData = await api.recordCatch(
    contract,
    textToBytes32(params.batchId),
    textToBytes32(params.region),
    textToBytes32(params.catchDate),
    textToBytes32(params.fishSpecies),
    fishManifest,
    photoHash,
    BigInt(Math.floor(Date.now() / 1000)),
    // v3: GPS bounding box for range proof
    degreesToUint32(params.latMin),
    degreesToUint32(params.latMax),
    degreesToUint32(params.lonMin),
    degreesToUint32(params.lonMax),
  );

  return {
    txId: txData.txId,
    blockHeight: txData.blockHeight as bigint | number,
    blockHash: txData.blockHash ?? undefined,
    photoHashHex: hexFromBytes(photoHash),
  };
};

const parseFlag = (args: string[], flag: string): string | undefined => {
  const i = args.indexOf(flag);
  if (i === -1) return undefined;
  const value = args[i + 1];
  if (value === undefined || value.startsWith('--')) {
    throw new Error(`${flag} requires a value`);
  }
  return value;
};

// Derive the owner public key from a 32-byte secret key, using the same
// domain-tagged persistentHash as the on-chain `publicKey(sk)` pure circuit.
// We invoke the compiled contract's pureCircuits so this TS-side derivation
// can never drift from the Compact source — the formula lives in one place.
const derivePublicKeyFromSk = (sk: Uint8Array): Uint8Array => {
  const out = pureCircuits.publicKey(sk);
  if (!(out instanceof Uint8Array) || out.length !== 32) {
    throw new Error(`pureCircuits.publicKey returned unexpected value: ${out}`);
  }
  return out;
};

const cmdDeploy = async (config: Config, logger: Logger, args: string[]): Promise<void> => {
  const initialOwnerHex = parseFlag(args, '--initial-owner');
  if (!initialOwnerHex) {
    throw new Error(
      'Usage: deploy --initial-owner <hex32>\n' +
      '  hex32 is the 64-char hex of the admin public key, derived from the admin secret key.\n' +
      '  Run `npm run preview -- derive-owner-pk` (or :preprod / :mainnet) to print it from the on-disk admin-sk.',
    );
  }
  const initialOwner = hexToBytes(initialOwnerHex);
  if (initialOwner.length !== 32) {
    throw new Error(`--initial-owner must decode to 32 bytes, got ${initialOwner.length}`);
  }
  api.setLogger(logger);
  const walletCtx = await api.buildWalletAndWaitForFunds(config, readSeed());
  try {
    const providers = await api.withStatus('Configuring providers', () =>
      api.configureProviders(walletCtx, config),
    );
    const contract = await api.withStatus('Deploying contract', () =>
      api.deploy(providers, initialOwner),
    );
    const address = contract.deployTxData.public.contractAddress;
    const file = contractAddressFile();
    writeFileSync(file, address);
    logger.info(
      { file, address, initialOwner: hexFromBytes(initialOwner) },
      'Saved contract address.',
    );
  } finally {
    // Save latest sync state before stop (no-op when walletStateDir not configured).
    await api.saveWalletStates(walletCtx.wallet, config.walletStateDir);
    await walletCtx.wallet.stop();
  }
};

const cmdRotateOwner = async (config: Config, logger: Logger, args: string[]): Promise<void> => {
  const newOwnerHex = parseFlag(args, '--new-owner');
  if (!newOwnerHex) {
    throw new Error(
      'Usage: rotate-owner --new-owner <hex32>\n' +
      '  hex32 is the 64-char hex of the new owner public key. The current admin secret key\n' +
      '  must be available via the admin-sk file or GYOTAK_MIDNIGHT_ADMIN_SK env var; the\n' +
      '  contract assert(publicKey(localSecretKey()) == owner) gates this call.',
    );
  }
  const newOwner = hexToBytes(newOwnerHex);
  if (newOwner.length !== 32) {
    throw new Error(`--new-owner must decode to 32 bytes, got ${newOwner.length}`);
  }
  // Fail fast if the admin secret key is unreadable, before we spin up a wallet.
  loadAdminSecretKey();

  api.setLogger(logger);
  const walletCtx = await api.buildWalletAndWaitForFunds(config, readSeed());
  try {
    const providers = await api.withStatus('Configuring providers', () =>
      api.configureProviders(walletCtx, config),
    );
    const contract = await api.joinContract(providers, readContractAddress());
    const txData = await api.withStatus('Submitting rotateOwner', () =>
      api.rotateOwner(contract, newOwner),
    );
    console.log('');
    console.log('  ─ rotateOwner TX submitted');
    console.log(`    txId:        ${txData.txId}`);
    console.log(`    blockHeight: ${txData.blockHeight}`);
    console.log(`    blockHash:   ${txData.blockHash ?? '(n/a)'}`);
    console.log(`    newOwner:    ${hexFromBytes(newOwner)}`);
    console.log('');
  } finally {
    await api.saveWalletStates(walletCtx.wallet, config.walletStateDir);
    await walletCtx.wallet.stop();
  }
};

const cmdDeriveOwnerPk = (): void => {
  // Read sk from the standard source (file or env) and print the matching pk.
  // Ergonomic helper for the deploy ritual; never logs or echoes the secret key.
  const sk = loadAdminSecretKey();
  const pk = derivePublicKeyFromSk(sk);
  console.log(hexFromBytes(pk));
};

const cmdRecordCatch = async (config: Config, logger: Logger, args: string[]): Promise<void> => {
  const nonceFlag = parseFlag(args, '--nonce');
  // Remove --nonce <value> from args before positional parsing
  const positional = args.filter((_, i) => {
    if (args[i] === '--nonce') return false;
    if (i > 0 && args[i - 1] === '--nonce') return false;
    return true;
  });
  const [batchId, region, catchDate, fishSpecies, photoUrl, gpsLat, gpsLng, latMinStr, latMaxStr, lonMinStr, lonMaxStr, fishItemsJson] = positional;
  if (!batchId || !region || !catchDate || !fishSpecies || !photoUrl || !gpsLat || !gpsLng || !latMinStr || !latMaxStr || !lonMinStr || !lonMaxStr) {
    throw new Error(
      'Usage: record-catch <batchId> <region> <catchDate> <fishSpecies> <photoUrl> <gpsLat> <gpsLng> <latMin> <latMax> <lonMin> <lonMax> [fishItemsJson] [--nonce <64hex>]\n' +
      '  latMin/latMax/lonMin/lonMax: GPS bounding box in degrees (v3 range proof).\n' +
      '  --nonce: optional 32-byte hex nonce for GPS hiding commitment.\n' +
      '           If omitted, a random nonce is generated and printed.\n' +
      '           The nonce is NOT persisted to D1 (use mirror-pending for production).\n' +
      '  fishItemsJson (optional): catch_reports.fish_items JSON; builds the v2 fishManifest.\n' +
      '  Omit it to record an all-zero manifest.',
    );
  }
  const fishManifest = buildFishManifest(fishItemsJson ?? null);

  // Fetch photo and compute SHA-256 of its bytes.
  logger.info({ photoUrl }, 'Fetching photo for hashing...');
  const resp = await fetch(photoUrl);
  if (!resp.ok) {
    throw new Error(`Failed to fetch photo: ${resp.status} ${resp.statusText}`);
  }
  const photoBytes = new Uint8Array(await resp.arrayBuffer());
  const photoHash = await sha256(photoBytes);
  logger.info(
    { photoBytes: photoBytes.byteLength, photoHash: hexFromBytes(photoHash) },
    'photo sha256 computed',
  );

  // v3: register GPS coords directly (replaces broken GPS_JSON file mechanism).
  registerGpsCoords(batchId, degreesToUint32(gpsLat), degreesToUint32(gpsLng));

  // v3: nonce for GPS hiding commitment (in-memory only, NOT persisted to D1).
  let nonce: Uint8Array;
  if (nonceFlag) {
    const clean = nonceFlag.replace(/^0x/i, '');
    if (!/^[0-9a-fA-F]{64}$/.test(clean)) {
      throw new Error(`--nonce must be 64 hex characters, got ${clean.length}`);
    }
    nonce = Uint8Array.from(clean.match(/.{2}/g)!.map((b) => parseInt(b, 16)));
  } else {
    nonce = randomBytes(32);
    console.log(`  generated nonce: ${Buffer.from(nonce).toString('hex')}`);
  }
  registerGpsNonce(batchId, nonce);

  api.setLogger(logger);
  const walletCtx = await api.buildWalletAndWaitForFunds(config, readSeed());
  try {
    const providers = await api.withStatus('Configuring providers', () =>
      api.configureProviders(walletCtx, config),
    );
    const contract = await api.joinContract(providers, readContractAddress());

    const txData = await api.withStatus('Submitting recordCatch', () =>
      api.recordCatch(
        contract,
        textToBytes32(batchId),
        textToBytes32(region),
        textToBytes32(catchDate),
        textToBytes32(fishSpecies),
        fishManifest,
        photoHash,
        BigInt(Math.floor(Date.now() / 1000)),
        degreesToUint32(latMinStr),
        degreesToUint32(latMaxStr),
        degreesToUint32(lonMinStr),
        degreesToUint32(lonMaxStr),
      ),
    );

    console.log('');
    console.log('  ─ recordCatch TX submitted');
    console.log(`    txId:        ${txData.txId}`);
    console.log(`    blockHeight: ${txData.blockHeight}`);
    console.log(`    blockHash:   ${txData.blockHash ?? '(n/a)'}`);
    console.log(`    photoHash:   ${hexFromBytes(photoHash)}`);
    console.log(`    nonce:       ${Buffer.from(nonce).toString('hex')}`);
    console.log('');
  } finally {
    await api.saveWalletStates(walletCtx.wallet, config.walletStateDir);
    await walletCtx.wallet.stop();
  }
};

const cmdVerifyCatch = async (config: Config, logger: Logger, args: string[]): Promise<void> => {
  const [batchId] = args;
  if (!batchId) {
    throw new Error('Usage: verify-catch <batchId>');
  }
  api.setLogger(logger);
  const walletCtx = await api.buildWalletAndWaitForFunds(config, readSeed());
  try {
    const providers = await api.withStatus('Configuring providers', () =>
      api.configureProviders(walletCtx, config),
    );

    const onChain = await api.getCatchLedgerState(
      providers,
      readContractAddress() as any,
      hexFromBytes(textToBytes32(batchId)),
    );
    if (!onChain) {
      throw new Error(`No catch record found for batchId=${batchId}`);
    }

    console.log('');
    console.log('  ─ CatchRecord (read from ledger)');
    console.log(`    batchId:     ${batchId}`);
    console.log(`    regionLabel: ${bytes32ToAscii(onChain.regionLabel)}`);
    console.log(`    catchDate:   ${bytes32ToAscii(onChain.catchDate)}`);
    console.log(`    fishSpecies: ${bytes32ToAscii(onChain.fishSpecies)}`);
    console.log(`    gpsCommitment: ${hexFromBytes(onChain.gpsCommitment)}`);
    console.log(`    photoHash:   ${hexFromBytes(onChain.photoHash)}`);
    console.log(`    committedAt: ${onChain.committedAt} (${new Date(Number(onChain.committedAt) * 1000).toISOString()})`);
    console.log('');
  } finally {
    // Save latest sync state before stop (no-op when walletStateDir not configured).
    await api.saveWalletStates(walletCtx.wallet, config.walletStateDir);
    await walletCtx.wallet.stop();
  }
};

export const run = async (config: Config, logger: Logger): Promise<void> => {
  const [, , cmd, ...rest] = process.argv;
  try {
    switch (cmd) {
      case 'deploy':
        await cmdDeploy(config, logger, rest);
        break;
      case 'record-catch':
        await cmdRecordCatch(config, logger, rest);
        break;
      case 'verify-catch':
        await cmdVerifyCatch(config, logger, rest);
        break;
      case 'rotate-owner':
        await cmdRotateOwner(config, logger, rest);
        break;
      case 'derive-owner-pk':
        cmdDeriveOwnerPk();
        break;
      default:
        console.error(
          'Usage: cli <deploy|record-catch|verify-catch|rotate-owner|derive-owner-pk> [...args]',
        );
        process.exit(1);
    }
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    logger.error({ err: msg, stack: e instanceof Error ? e.stack : undefined }, 'Command failed.');
    process.exit(1);
  }
  logger.info('Goodbye.');
};
